defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "parti.xyz"
    footer_text: "<3"
  authenticators:
    parti_database:
      authenticator: "Parti"
      options:
        table: "users"
        username_column: "email"
        password_column: "password_digest"
        extra_attributes:
          nickname: "nickname"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
