defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"
  authenticators:
    parti_database:
      authenticator: "ActiveRecord"
      options:
        table: "users"
        username_column: "username"
        password_column: "password_digest"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
